ECE297 Storage Server: storage.c File Reference
storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <errno.h>
#include "storage.h"
#include "client.h"
#include "utils.h"
#include <sys/time.h>
Defines
#define LOGGING 1
Functions
void * storage_connect (const char *hostname, const int port)
Establish a connection to the server.
int storage_auth (const char *username, const char *passwd, void *conn)
This is the authentication function, this function will send the client information to the server and verify that information with the deafult.conf file. Once the information has been verified this function will return a code depending on the status of the verification. if it returned 0 then the authentication is successful. If another number is returned however, then an error occured. The type of error is determined by the code that is returned.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_query (const char *table, const char *predicates, char **keys, const int max_keys, void *conn)
Query the table for records, and retrieve the matching keys.
int storage_disconnect (void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
Variables
int AUTH_STATUS = 1
char holder [100]
FILE * fpCLIENT = NULL
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h.
Definition in file storage.c.
Function Documentation
int storage_auth (const char * username, const char * passwd, void * conn)
This is the authentication function, this function will send the client information to the server and verify that information with the deafult.conf file. Once the information has been verified this function will return a code depending on the status of the verification. if it returned 0 then the authentication is successful. If another number is returned however, then an error occured. The type of error is determined by the code that is returned.
Authenticate the client's connection to the server.
Definition at line 105 of file storage.c.
References ERR_AUTHENTICATION_FAILED, generate_encrypted_password(), recvline(), and sendall().
Referenced by main().
void* storage_connect (const char * hostname, const int port)
Establish a connection to the server.
Parameters:
hostname The IP address or hostname of the server.
port The TCP port of the server.
Returns:
If successful, return a pointer to a data structure that represents a connection to the server. Otherwise return NULL.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, or ERR_UNKNOWN.
Client connects! REASONING: We will have to ensure that the user correctly enters the required hostname and password. we will LOG what the user enters for the hostname and password, as well as what time they connect. NOTE: If this log does not get written, the client has likely not entered a valid hostname and/or password LOGGER 1! If connection to server not made, return NULL, ELSE if connection made, return socket value (integer).
Definition at line 31 of file storage.c.
References currentDateTime(), and logger().
Referenced by main().
int storage_disconnect (void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Close the connection to the server.
Definition at line 514 of file storage.c.
References currentDateTime(), and logger().
Referenced by main().
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Retrieve the value associated with a key in a table.
Definition at line 174 of file storage.c.
References ERR_KEY_NOT_FOUND, ERR_TABLE_NOT_FOUND, logger(), recvline(), sendall(), valid_string_check(), and storage_record::value.
Referenced by main().
int storage_query (const char * table, const char * predicates, char ** keys, const int max_keys, void * conn)
Query the table for records, and retrieve the matching keys.
Parameters:
table A table in the database.
predicates A comma separated list of predicates.
keys An array of strings where the keys whose records match the specified predicates will be copied. The array must have room for at least max_keys elements. The caller must allocate memory for this array.
max_keys The size of the keys array.
conn A connection to the server.
Returns:
Return the number of matching keys (which may be more than max_keys) if successful, and -1 otherwise.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, ERR_TABLE_NOT_FOUND, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, or ERR_UNKNOWN.
Each predicate consists of a column name, an operator, and a value, each separated by optional whitespace. The operator may be a "=" for string types, or one of "<, >, =" for int and float types. An example of query predicates is "name = bob, mark > 90".
Definition at line 368 of file storage.c.
References ERR_INVALID_PARAM, ERR_TABLE_NOT_FOUND, logger(), MAX_KEY_LEN, recvline(), sendall(), and valid_string_check().
Referenced by main().
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Store a key/value pair in a table.
Definition at line 263 of file storage.c.
References currentDateTime(), logger(), recvline(), sendall(), valid_string_check(), and storage_record::value.
Referenced by main().