ECE297 Storage Server: storage.h File Reference
storage.h File Reference
This file defines the interface between the storage client and server.
#include <stdint.h>
Classes
struct storage_record
Encapsulate the value associated with a key in a table.
Defines
#define MAX_CONFIG_LINE_LEN 1024
Max characters in each config file line.
#define MAX_USERNAME_LEN 64
Max characters of server username.
#define MAX_ENC_PASSWORD_LEN 64
Max characters of server's encrypted password.
#define MAX_HOST_LEN 64
Max characters of server hostname.
#define MAX_PORT_LEN 8
Max characters of server port.
#define MAX_PATH_LEN 256
Max characters of data directory path.
#define MAX_TABLES 100
Max tables supported by the server.
#define MAX_RECORDS_PER_TABLE 1000
Max records per table.
#define MAX_TABLE_LEN 20
Max characters of a table name.
#define MAX_KEY_LEN 20
Max characters of a key name.
#define MAX_CONNECTIONS 10
Max simultaneous client connections.
#define MAX_COLUMNS_PER_TABLE 10
Max columns per table.
#define MAX_COLNAME_LEN 20
Max characters of a column name.
#define MAX_STRTYPE_SIZE 40
Max SIZE of string types.
#define MAX_VALUE_LEN 800
Max characters of a value.
#define ERR_INVALID_PARAM 1
A parameter is not valid.
#define ERR_CONNECTION_FAIL 2
Error connecting to server.
#define ERR_NOT_AUTHENTICATED 3
Client not authenticated.
#define ERR_AUTHENTICATION_FAILED 4
Client authentication failed.
#define ERR_TABLE_NOT_FOUND 5
The table does not exist.
#define ERR_KEY_NOT_FOUND 6
The key does not exist.
#define ERR_UNKNOWN 7
Any other error.
#define ERR_TRANSACTION_ABORT 8
Transaction abort error.
Functions
void * storage_connect (const char *hostname, const int port)
Establish a connection to the server.
int storage_auth (const char *username, const char *passwd, void *conn)
Authenticate the client's connection to the server.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
Retrieve the value associated with a key in a table.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
Store a key/value pair in a table.
int storage_query (const char *table, const char *predicates, char **keys, const int max_keys, void *conn)
Query the table for records, and retrieve the matching keys.
int storage_disconnect (void *conn)
Close the connection to the server.
Detailed Description
This file defines the interface between the storage client and server.
The functions here should be implemented in storage.c.
You should not modify this file, or else the code used to mark your implementation will break.
Definition in file storage.h.
Function Documentation
int storage_auth (const char * username, const char * passwd, void * conn)
Authenticate the client's connection to the server.
Parameters:
username Username to access the storage server.
passwd Password in its plain text form.
conn A connection to the server.
Returns:
Return 0 if successful, and -1 otherwise.
On error, errno will be set to ERR_AUTHENTICATION_FAILED.
Definition at line 105 of file storage.c.
References ERR_AUTHENTICATION_FAILED, generate_encrypted_password(), recvline(), and sendall().
Referenced by main().
void* storage_connect (const char * hostname, const int port)
Establish a connection to the server.
Parameters:
hostname The IP address or hostname of the server.
port The TCP port of the server.
Returns:
If successful, return a pointer to a data structure that represents a connection to the server. Otherwise return NULL.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, or ERR_UNKNOWN.
Client connects! REASONING: We will have to ensure that the user correctly enters the required hostname and password. we will LOG what the user enters for the hostname and password, as well as what time they connect. NOTE: If this log does not get written, the client has likely not entered a valid hostname and/or password LOGGER 1! If connection to server not made, return NULL, ELSE if connection made, return socket value (integer).
Definition at line 31 of file storage.c.
References currentDateTime(), and logger().
Referenced by main().
int storage_disconnect (void * conn)
Close the connection to the server.
Parameters:
conn A pointer to the connection structure returned in an earlier call to storage_connect().
Returns:
Return 0 if successful, and -1 otherwise.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, or ERR_UNKNOWN.
Definition at line 514 of file storage.c.
References currentDateTime(), and logger().
Referenced by main().
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
Retrieve the value associated with a key in a table.
Parameters:
table A table in the database.
key A key in the table.
record A pointer to a record struture.
conn A connection to the server.
Returns:
Return 0 if successful, and -1 otherwise.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, ERR_TABLE_NOT_FOUND, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, or ERR_UNKNOWN.
The record with the specified key in the specified table is retrieved from the server using the specified connection. If the key is found, the record structure is populated with the details of the corresponding record. Otherwise, the record structure is not modified.
Definition at line 174 of file storage.c.
References ERR_KEY_NOT_FOUND, ERR_TABLE_NOT_FOUND, logger(), recvline(), sendall(), valid_string_check(), and storage_record::value.
Referenced by main().
int storage_query (const char * table, const char * predicates, char ** keys, const int max_keys, void * conn)
Query the table for records, and retrieve the matching keys.
Parameters:
table A table in the database.
predicates A comma separated list of predicates.
keys An array of strings where the keys whose records match the specified predicates will be copied. The array must have room for at least max_keys elements. The caller must allocate memory for this array.
max_keys The size of the keys array.
conn A connection to the server.
Returns:
Return the number of matching keys (which may be more than max_keys) if successful, and -1 otherwise.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, ERR_TABLE_NOT_FOUND, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, or ERR_UNKNOWN.
Each predicate consists of a column name, an operator, and a value, each separated by optional whitespace. The operator may be a "=" for string types, or one of "<, >, =" for int and float types. An example of query predicates is "name = bob, mark > 90".
Definition at line 368 of file storage.c.
References ERR_INVALID_PARAM, ERR_TABLE_NOT_FOUND, logger(), MAX_KEY_LEN, recvline(), sendall(), and valid_string_check().
Referenced by main().
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
Store a key/value pair in a table.
Parameters:
table A table in the database.
key A key in the table.
record A pointer to a record struture.
conn A connection to the server.
Returns:
Return 0 if successful, and -1 otherwise.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, ERR_TABLE_NOT_FOUND, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, or ERR_UNKNOWN.
The key and record are stored in the table of the database using the connection. If the key already exists in the table, the corresponding record is updated with the one specified here. If the key exists in the table and the record is NULL, the key/value pair are deleted from the table.
Definition at line 263 of file storage.c.
References currentDateTime(), logger(), recvline(), sendall(), valid_string_check(), and storage_record::value.
Referenced by main().