ECE297 Storage Server: TreeEntry.c File Reference
TreeEntry.c File Reference
GET and SET OPERATION are implemented here.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "TreeEntry.h"
#include "TreeDB.h"
#include "storage.h"
Functions
struct TreeEntry * createTable (char *name)
EVERY TABLE HAS AN ENTRY, so we create a TABLE with a key, value, and table-name.
void deleteTable (struct TreeEntry *table)
SAFELY REMOVE THE TABLE.
void setTableName (struct TreeEntry *table, char *name)
TABLES ARE DEFINED BY NAMES. HERE WE WILL ASSIGN THE NAME TO THE TABLE.
char * getTableName (struct TreeEntry *table)
char * getEntryValue (struct TreeEntry *table)
void setEntryValue (struct TreeEntry *table, char *_value)
sets entry value to _value
void printTable (struct TreeEntry *table)
prints the name of the table
Detailed Description
GET and SET OPERATION are implemented here.
Definition in file TreeEntry.c.
Function Documentation
char* getEntryValue (struct TreeEntry * table)
Returns:
returns string to entry value
Definition at line 88 of file TreeEntry.c.
char* getTableName (struct TreeEntry * table)
Returns:
RETURN THE TABLE NAME
Definition at line 76 of file TreeEntry.c.
Referenced by findTable(), insertTable(), and printTable().