ECE297 Storage Server: utils.h File Reference
utils.h File Reference
This file declares various utility functions that are can be used b y the storage server and client library.
#include <errno.h>
#include <stdio.h>
#include "storage.h"
#include <sys/time.h>
Classes
struct config_params
A struct to store config parameters.
struct table
struct configuration
Defines
#define MAX_CMD_LEN (1024 * 8)
The max length in bytes of a command from the client to the server.
#define LOG(x) {printf x; fflush(stdout);}
A macro to log some information.
#define DBG(x) {printf x; fflush(stdout);}
A macro to output debug information.
#define DEFAULT_CRYPT_SALT "xx"
Functions
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int read_config (const char *config_file, config_params *params)
Read and load configuration parameters.
void logger (FILE *file, char *message, int LOGGER)
Generates a log message.
char * currentDateTime ()
Default two character salt used for password encryption.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
int valid_string_check (char *input, int value)
This "valid_string_check" function will take in a string and check whether this string contains the proper ASCII values from A-Z and 0-9. If it is then the function returns a zero if not then the function returns another value.
char * add_delimiter (char *input)
this function will replace all the spaces within a string into a '#' for storing purposes in the value.
char * undo_delimiter (char *input)
this function will replace all the '#' within a string into a ' ' for retrieving purposes in the value.
int timeval_subtract (struct timeval *result, struct timeval *t2, struct timeval *t1)
The following two functions below are used to time the execution time of the server, and the storage. "timeval_subtract" subtracts final and the initial value to get the elapsed time. "timeval_print" will print out the value of "timeval_subtract".
void timeval_print (struct timeval *tv)
int type_identifier (char string[800])
The type_identifier function will receive a string and check whether it is all numbers or not. if it is all integers we return 0 identifying that the string sent is an integer else we send 0 which identifies that the string sent is a char value.
int size_get (char string[800])
Variables
struct configuration * c
struct table * tl
struct table * t
Detailed Description
This file declares various utility functions that are can be used b y the storage server and client library.
Definition in file utils.h.
Define Documentation
#define DBG (x) {printf x; fflush(stdout);}
A macro to output debug information.
It is only enabled in debug builds.
Definition at line 46 of file utils.h.
#define LOG (x) {printf x; fflush(stdout);}
A macro to log some information.
Use it like this: LOG(("Hello %s", "world\n"))
Don't forget the double parentheses, or you'll get weird errors!
Definition at line 34 of file utils.h.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters:
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns:
Returns encrypted password.
Definition at line 207 of file utils.c.
Referenced by storage_auth().
void logger (FILE * file, char * message, int LOGGER)
Generates a log message.
Parameters:
file The output stream
message Message to log.
Definition at line 180 of file utils.c.
Referenced by main(), storage_connect(), storage_disconnect(), storage_get(), storage_query(), and storage_set().
int read_config (const char * config_file, config_params * params)
Read and load configuration parameters.
Parameters:
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns:
Return 0 on success, -1 otherwise.
Definition at line 126 of file utils.c.
References process_config_line().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
Returns:
Return 0 on success, -1 otherwise.
In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Definition at line 40 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), storage_query(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns:
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Definition at line 20 of file utils.c.
Referenced by storage_auth(), storage_get(), storage_query(), and storage_set().